[versions]
agp = "8.5.0"

android-tools = "31.5.0"

androidx-annotation = "1.8.0"
androidx-core-ktx = "1.13.1"
androidx-lifecycle = "2.8.2"
androidx-activity-compose = "1.9.0"
androidx-compose-bom = "2024.06.00"
androidx-room = "2.6.1"
androidx-datastore = "1.1.1"

kotlin-android = "2.0.0"
kotlinx-coroutines = "1.9.0-RC"
kotlinx-serialization-json = "1.7.0"
kotlinx-immutable = "0.3.7"

bundletool = "1.15.6"
ksp = "2.0.0-1.0.21"
truth = "1.4.2"

dagger = "2.51.1"
hilt = "1.2.0"
javax-inject = "1"

junit = "4.13.2"

google-protobuf-plugin = "0.9.4"
google-protobuf = "3.25.3"

androidx-test-ext-junit = "1.1.5"
androidx-test-espresso-core = "3.5.1"

detekt = "1.23.6"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.2.4"
profileinstaller = "1.3.1"
detekt-rules-compose = "0.4.3"

# Used directly in gradle plugins

androidSdk-min = "21"
androidSdk-compile = "34"
androidSdk-target = "34"

appVersion-name = "0.1.0"
appVersion-code = "1"

# TODO обновить до 19 или 22
jvm = "17"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-unit = { module = "androidx.compose.ui:ui-unit" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }

bundletool = { module = "com.android.tools.build:bundletool", version.ref = "bundletool" }

jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-android" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
jetbrains-kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
google-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "google-protobuf" }
google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "google-protobuf" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
dagger-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-main = { module = "com.google.dagger:dagger", version.ref = "dagger" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }

junit = { module = "junit:junit", version.ref = "junit" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

detekt-rules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-rules-compose" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

# Project internal convention plugin
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin-android" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-android" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradle-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidx-room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-android" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-android" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-protobuf = { id = "com.google.protobuf", version.ref = "google-protobuf-plugin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
android-test = { id = "com.android.test", version.ref = "agp" }

# Project internal convention plugins
app-android-application = { id = "app.android.application", version = "unspecified" }
app-android-library = { id = "app.android.library", version = "unspecified" }
app-android-compose = { id = "app.android.compose", version = "unspecified" }
app-jvm = { id = "app.jvm", version = "unspecified" }
app-android-hilt = { id = "app.android.hilt", version = "unspecified" }
app-android-room = { id = "app.android.room", version = "unspecified" }
app-feature-ui = { id = "app.feature.ui", version = "unspecified" }
app-feature-domain = { id = "app.feature.domain", version = "unspecified" }
app-feature-data = { id = "app.feature.data", version = "unspecified" }
app-feature-nav = { id = "app.feature.nav", version = "unspecified" }